config/routes.rb
Rails.application.routes.draw do
  root 'links#index'

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:new, :create]
  get "authentication"  => "static_pages#index"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :links, only: [:index, :create, :destroy, :update]
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :title, presence: true
  validates :url, presence: true
  validates :url, :url => true
  validates :read, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true
  validates_confirmation_of :password
  has_secure_password
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    protect_from_forgery with: :null_session
  end
end

app/controllers/api/v1/links_controller.rb
module Api
  module V1
    class LinksController < ApiController
      respond_to :json

      def index
        respond_with Link.all
      end

      def create
        link = Link.new(link_params)

        if link.save
          render json: link
        else
          render json: "Invalid url"
        end
      end

      def destroy
        render json: Link.destroy(params[:id])
      end

      def update
        link = Link.update(params["id"], link_params)
        if link.save
          render json: link
        else
          render json: {status: :failure, error: "Invalid url", link: Link.find(params["id"])}
        end
      end

      private

      def link_params
        params.require(:link).permit(:title, :url, :read)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    if !current_user
      redirect_to authentication_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index

  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:error] = "Invalid Login"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:error] = "Invalid Input"
      render :new
    end
  end

private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thoughtbox</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/index.html.erb
<div id="flash">Invalid url</div>
<h1>Links Index</h1>
<%= link_to "Sign Out", logout_path, method: :delete %>

<h3>Add a new link!</h3>
<form id="new-link" class="form-inline">
  <%= text_field_tag :title, nil, placeholder: "Luxurious Title", class: 'form-control' %>
  <%= text_field_tag :url, nil, placeholder: "What's your link?!", class: 'form-control' %>
<button type="button" name="button" class="btn btn-success" id="save">Save!</button>
</form>

<h3>Check out these links!!</h3>
<button type="button" name="button" class="btn btn-success" id="filter-read">Read</button>
<button type="button" name="button" class="btn btn-info" id="filter-unread">Unread</button>

<h4>Search!</h4>

<form class="navbar-form" role="search">
  <div class="form-group has-feedback">
      <input id='search-box' class="form-control" type="text" placeholder="Search ideas!">
    <i class="glyphicon glyphicon-search form-control-feedback"></i>
  </div>
</form>

<div>
  <ul id="links-list">
  </ul>
</div>

app/views/static_pages/index.html.erb
<%= link_to "Log In", login_path %> or
<%= link_to "Sign Up", new_user_path %>

app/views/users/new.html.erb
<div class="login">

<div class="text-center">
  <h1>Please sign up</h1>
  <%= form_for(@user) do |f| %>
    <h4><%= f.label :email %></h4>
    <h4><%= f.text_field :email %></h4>
    <h4><%= f.label :password %></h4>
    <h4><%= f.password_field :password %></h4>
    <h4><%= f.label :password_confirmation %></h4>
    <h4> <%= f.password_field :password_confirmation %> </h4>
    <%= f.submit "Create Account", class: "btn btn-primary btn-font-size" %>
  <% end %>
</div>
</div>

<h1>Already a user? </h1>
<h4> <%= link_to "login here", login_path %> </h4>

app/views/users/show.html.erb
<h1>logged_in_as_<%= current_user.email %></h1>
<li><%= link_to "logout", logout_path, method: :delete %></li>